{% set name = "sentinelsat" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3946d8b7bc8ce3392701d90c80fd7068013e44d9ebf947dc0871d6d86ed40a88

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sentinelsat = sentinelsat.scripts.cli:cli

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - click
    - html2text
    - geojson >=2
    - tqdm
    - six
    - geomet

test:
  imports:
    - sentinelsat
  commands:
    - sentinelsat --help
  #   - python -m pytest --pyargs sentinelsat
  # requires:
  #   - pandas
  #   - geopandas
  #   - shapely
  #   - pytest >=3.6.3
  #   - pytest-vcr      # not in conda-forge
  #   - pytest-socket
  #   - requests-mock
  #   - pyyaml
  #   - rstcheck
  # source_files:
  #   - tests

about:
  home: https://github.com/sentinelsat/sentinelsat
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Search and download Copernicus Sentinel satellite images
  description: |
    Sentinelsat makes searching, downloading and retrieving the metadata
    of Sentinel satellite images from the Copernicus Open Access Hub easy.
    It offers an easy-to-use command line interface and a powerful Python API.
  doc_url: https://sentinelsat.readthedocs.io
  dev_url: https://github.com/sentinelsat/sentinelsat

extra:
  recipe-maintainers:
    - avalentino
